/**
 * CDN edge cache (Cache API) helpers — P0-2 fix (2026-08-05).
 *
 * The public worker runs on a Workers custom domain, so zone-level Cache
 * Rules / edge TTL never apply to responses generated by the worker itself
 * ("Workers sits in front of the cache" — SSR pages carry no cf-cache-status).
 * The fix: cache cacheable GET responses in `caches.default` from the OpenNext
 * wrapper (open-next.config.ts) and purge them from /api/revalidate.
 *
 * Caching is strictly opt-in: only responses whose origin Cache-Control
 * carries an explicit `s-maxage` (the AGENTS.md §3 TTL matrix) are stored.
 * RSC / router-prefetch requests are never cached and never served from cache
 * (their HTML twin is keyed by the same URL).
 */

/** Tag format shared with OpenNext's cachePurge component (`_N_T_<path>`). */
export const CACHE_TAG_PREFIX = '_N_T_'

/** RSC / router-prefetch / segment-prefetch requests carry one of these. */
const NON_HTML_NAVIGATION_HEADERS = [
  'rsc',
  'next-router-state-tree',
  'next-router-prefetch',
  'next-router-segment-prefetch',
] as const

/**
 * True for plain browser navigations (and plain GET probes) that may be
 * served from / stored in the CDN edge cache. Non-GET methods, /api/* and
 * /_next/* paths, and RSC / router-prefetch requests are never cached.
 */
export function isHtmlNavigationRequest(request: Request): boolean {
  if (request.method !== 'GET') return false
  const { pathname } = new URL(request.url)
  if (pathname.startsWith('/api/')) return false
  if (pathname.startsWith('/_next/')) return false
  return NON_HTML_NAVIGATION_HEADERS.every((h) => request.headers.get(h) === null)
}

/**
 * True for responses we are allowed to store: 2xx with an explicit s-maxage
 * opt-in from the origin. /api/* never reaches this point (see
 * isHtmlNavigationRequest) and /api/preview is `no-store` anyway.
 */
export function isCacheableResponse(response: Response): boolean {
  if (response.status < 200 || response.status >= 300) return false
  const cacheControl = response.headers.get('cache-control') ?? ''
  return /(^|,)\s*s-maxage\s*=\s*\d+/.test(cacheControl)
}

/**
 * Cache-Tag attached to every stored copy so the whole CDN can be invalidated
 * globally from /api/revalidate via the purge API (`cache.delete` alone only
 * clears the data center the request lands in).
 */
export function cdnTagForPath(path: string): string {
  const normalized = path.startsWith('/') ? path : `/${path}`
  return `${CACHE_TAG_PREFIX}${normalized}`
}

/**
 * Cache-Control for static assets. next.config.mjs headers() rules do not
 * reach file-server responses on Cloudflare Workers (the App Router file
 * server's default `public, max-age=0, must-revalidate` wins), so the wrapper
 * normalizes these paths itself. Mirrors the next.config.mjs sources
 * (/images/(.*), /_next/static/(.*), /fonts/(.*)) — keep in sync.
 */
export const STATIC_ASSET_CACHE_CONTROL = 'public, max-age=31536000, immutable'

/** True for the static asset paths that get STATIC_ASSET_CACHE_CONTROL. */
export function isStaticAssetPath(pathname: string): boolean {
  return (
    pathname.startsWith('/_next/static/') ||
    pathname.startsWith('/images/') ||
    pathname.startsWith('/fonts/')
  )
}
