PRAGMA foreign_keys = ON;
-- Pricing plans (UPSERT by fixed id)
INSERT INTO pricing_plans (id, key, price, old_price, currency, sort_order, status, created_at, updated_at) VALUES
('plan-free','free',0,NULL,'USD',0,'PUBLISHED','2026-08-07T11:00:45.169Z','2026-08-07T11:00:45.172Z'),
('plan-single','single',50,NULL,'USD',1,'PUBLISHED','2026-08-07T11:00:45.172Z','2026-08-07T11:00:45.172Z'),
('plan-premium','premium',210,250,'USD',2,'PUBLISHED','2026-08-07T11:00:45.172Z','2026-08-07T11:00:45.172Z'),
('plan-elite','elite',400,500,'USD',3,'PUBLISHED','2026-08-07T11:00:45.172Z','2026-08-07T11:00:45.172Z')
ON CONFLICT(id) DO UPDATE SET key=excluded.key, price=excluded.price, old_price=excluded.old_price, currency=excluded.currency, sort_order=excluded.sort_order, status=excluded.status, updated_at=excluded.updated_at;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-free-ru','plan-free','ru','Диагностическая консультация','15 минут · Знакомство и анализ запроса','Первичная онлайн-встреча для знакомства и определения направления работы',NULL,NULL,'["Определение корня проблемы","Рекомендации по формату работы","Без обязательств"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-free-uk','plan-free','uk','Діагностична консультація','15 хвилин · Знайомство та аналіз запиту','Первинна онлайн-зустріч для знайомства та визначення напрямку роботи',NULL,NULL,'["Визначення кореня проблеми","Рекомендації щодо формату роботи","Без зобов''язань"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-single-ru','plan-single','ru','Одиночная сессия','50–60 минут · Глубокая работа','или 2000 грн',NULL,NULL,'["Индивидуальная сессия гипнотерапии","Работа с вашим запросом","Мягкий эриксоновский гипноз","Домашние практики после сессии"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-single-uk','plan-single','uk','Одиночна сесія','50–60 хвилин · Глибока робота','або 2000 грн',NULL,NULL,'["Індивідуальна сесія гіпнотерапії","Робота з вашим запитом","М''який еріксонівський гіпноз","Домашні практики після сесії"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-premium-ru','plan-premium','ru','Курс «Премиум»','5 сессий · Решение проблемы','Полноценный курс для глубинной проработки (экономия 16%)','Выбор большинства',NULL,'["5 индивидуальных сессий по 60 минут","Работа с причиной, а не симптомами","Индивидуальная программа между сессиями","Аудио-медитации под ваш запрос","Поддержка в чате между сессиями"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-premium-uk','plan-premium','uk','Курс «Преміум»','5 сесій · Вирішення проблеми','Повноцінний курс для глибинного опрацювання (економія 16%)','Вибір більшості',NULL,'["5 індивідуальних сесій по 60 хвилин","Робота з причиною, а не симптомами","Індивідуальна програма між сесіями","Аудіо-медитації під ваш запит","Підтримка в чаті між сесіями"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-elite-ru','plan-elite','ru','Курс «Элит»','10 сессий · Полная трансформация','Максимальный курс для устойчивых изменений (экономия 20%)',NULL,NULL,'["10 индивидуальных сессий по 60 минут","Полная проработка всех блоков","Индивидуальные музыкальные программы","Глубинная регрессивная работа","Приоритетная запись","Поддержка в чате на весь период курса"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;
INSERT INTO pricing_plan_translations (id, plan_id, locale, title, subtitle, description, badge, note, features_json) VALUES
('plan-elite-uk','plan-elite','uk','Курс «Еліт»','10 сесій · Повна трансформація','Максимальний курс для стійких змін (економія 20%)',NULL,NULL,'["10 індивідуальних сесій по 60 хвилин","Повне опрацювання всіх блоків","Індивідуальні музичні програми","Глибинна регресивна робота","Пріоритетний запис","Підтримка в чаті на весь період курсу"]')
ON CONFLICT(id) DO UPDATE SET plan_id=excluded.plan_id, locale=excluded.locale, title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, badge=excluded.badge, note=excluded.note, features_json=excluded.features_json;