/**
 * SEO Content Seeder — reads TEMP/seo-content/*.json and generates SQL for D1.
 * Run: node scripts/seo-seed.mjs
 * Then: npx wrangler d1 execute podvarchan --file=TEMP/seo-content/seed.sql --remote
 * Then: node scripts/seo-revalidate.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { join } from 'path'

const DIR = 'TEMP/seo-content'
const now = () => new Date().toISOString()
const sqlEscape = (s) => (s ?? '').replace(/'/g, "''")

const sql = []

sql.push('-- SEO Content Seed — generated by seo-seed.mjs')
sql.push('-- Run: npx wrangler d1 execute podvarchan --file=TEMP/seo-content/seed.sql --remote')
sql.push('')

// ═══════════════════════════════════════════════════
// 0. PLACEHOLDER COVER IMAGES for blog posts
// ═══════════════════════════════════════════════════
sql.push('-- ═══ Placeholder Cover Images ═══')
const placeholderImages = [
  { id: 'img-blog-nostalgiya', slug: 'nostalgiya-po-rodine' },
  { id: 'img-blog-kulturnyy-shok', slug: 'kulturnyy-shok' },
  { id: 'img-blog-trevoga-pereezd', slug: 'trevoga-posle-pereezda' },
  { id: 'img-blog-odinochestvo', slug: 'odinochestvo-v-emigracii' },
  { id: 'img-blog-panika', slug: 'kak-ostanovit-panicheskuyu-ataku' },
  { id: 'img-blog-postoyannaya-trevoga', slug: 'postoyannaya-trevoga-bez-prichiny' },
  { id: 'img-blog-erikson', slug: 'chto-takoe-eriksonovskiy-gipnoz' },
  { id: 'img-blog-effektivnost', slug: 'effektivna-li-gipnoterapiya-onlajn' },
]
for (const img of placeholderImages) {
  const ts = now()
  sql.push(`INSERT OR IGNORE INTO media_assets (id, file_name, original_name, mime_type, size, public_url, alt_ru, title_ru, created_at) VALUES ('${img.id}', '${img.slug}.jpg', '${img.slug}.jpg', 'image/jpeg', 0, '/images/blog/${img.slug}.jpg', 'Обложка статьи', 'Обложка статьи', '${ts}');`)
}
sql.push('')

// ═══════════════════════════════════════════════════
// 1. BLOG CATEGORIES
// ═══════════════════════════════════════════════════
const categories = [
  { id: 'cat-emigraciya', slugBase: 'emigraciya', sortOrder: 10, ruName: 'Жизнь в эмиграции', ruSlug: 'emigraciya', ruDesc: 'Статьи о жизни в эмиграции: адаптация, ностальгия, культурный шок, одиночество.', ukName: 'Життя в еміграції', ukSlug: 'emigraciya', ukDesc: 'Статті про життя в еміграції: адаптація, ностальгія, культурний шок.' },
  { id: 'cat-trevoga', slugBase: 'trevoga', sortOrder: 20, ruName: 'Тревога и панические атаки', ruSlug: 'trevoga', ruDesc: 'Статьи о тревоге, панических атаках и способах справиться.', ukName: 'Тривога та панічні атаки', ukSlug: 'trevoga', ukDesc: 'Статті про тривогу, панічні атаки та способи впоратися.' },
  { id: 'cat-gipnoterapiya', slugBase: 'gipnoterapiya', sortOrder: 30, ruName: 'О гипнотерапии', ruSlug: 'gipnoterapiya', ruDesc: 'Статьи о гипнотерапии: метод, эффективность, частые вопросы.', ukName: 'Про гіпнотерапію', ukSlug: 'gipnoterapiya', ukDesc: 'Статті про гіпнотерапію: метод, ефективність, часті питання.' },
]

sql.push('-- ═══ Blog Categories ═══')
for (const c of categories) {
  const ts = now()
  sql.push(`INSERT OR IGNORE INTO blog_categories (id, slug_base, sort_order, status) VALUES ('${c.id}', '${c.slugBase}', ${c.sortOrder}, 'PUBLISHED');`)
  sql.push(`INSERT OR IGNORE INTO blog_category_translations (id, category_id, locale, slug, name, description) VALUES ('${c.id}-ru', '${c.id}', 'ru', '${c.ruSlug}', '${sqlEscape(c.ruName)}', '${sqlEscape(c.ruDesc)}');`)
  sql.push(`INSERT OR IGNORE INTO blog_category_translations (id, category_id, locale, slug, name, description) VALUES ('${c.id}-uk', '${c.id}', 'uk', '${c.ukSlug}', '${sqlEscape(c.ukName)}', '${sqlEscape(c.ukDesc)}');`)
}
sql.push('')

// ═══════════════════════════════════════════════════
// 2. NEW SERVICE PAGES (4)
// ═══════════════════════════════════════════════════
const newServiceFiles = ['svc-emigrant.json', 'svc-germaniya.json', 'svc-avstriya.json', 'svc-polsha.json']
sql.push('-- ═══ New Service Pages ═══')
for (const f of newServiceFiles) {
  const data = JSON.parse(readFileSync(join(DIR, f), 'utf8'))
  const ts = now()
  sql.push(`INSERT OR IGNORE INTO services (id, slug_base, icon, category, priority, status, featured, sort_order, created_at, updated_at) VALUES ('${data.id}', '${data.slugBase}', '🌍', 'emigration', 100, 'PUBLISHED', 1, 100, '${ts}', '${ts}');`)
  // RU
  const ru = data.ru
  sql.push(`INSERT OR IGNORE INTO service_translations (id, service_id, locale, slug, title, short_title, description, hero_title, hero_subtitle, cta_text, faq_json) VALUES ('${data.id}-ru', '${data.id}', 'ru', '${ru.slug}', '${sqlEscape(ru.title)}', '${sqlEscape(ru.shortTitle)}', '${sqlEscape(ru.description)}', '${sqlEscape(ru.heroTitle)}', '${sqlEscape(ru.heroSubtitle)}', '${sqlEscape(ru.ctaText)}', '${sqlEscape(ru.faqJson)}');`)
  // UK
  const uk = data.uk
  sql.push(`INSERT OR IGNORE INTO service_translations (id, service_id, locale, slug, title, short_title, description, hero_title, hero_subtitle, cta_text) VALUES ('${data.id}-uk', '${data.id}', 'uk', '${uk.slug}', '${sqlEscape(uk.title)}', '${sqlEscape(uk.shortTitle)}', '${sqlEscape(uk.description)}', '${sqlEscape(uk.heroTitle)}', '${sqlEscape(uk.heroSubtitle)}', '${sqlEscape(uk.ctaText)}');`)
  // SEO RU
  const seo = data.seo
  sql.push(`INSERT OR IGNORE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${data.id}-ru', 'service', '${data.id}', 'ru', '${sqlEscape(seo.title)}', '${sqlEscape(seo.description)}', '${seo.canonicalPath}', '${ts}', '${ts}');`)
  // SEO UK — use UK title/description if available, else derive from RU
  const ukSeoTitle = uk.title ? uk.title + ' | В. Подварчан' : seo.title
  const ukSeoDesc = uk.heroSubtitle || seo.description
  const ukCanonical = seo.canonicalPath.replace('/ru/', '/uk/')
  sql.push(`INSERT OR IGNORE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${data.id}-uk', 'service', '${data.id}', 'uk', '${sqlEscape(ukSeoTitle)}', '${sqlEscape(ukSeoDesc)}', '${ukCanonical}', '${ts}', '${ts}');`)
  // FAQ items
  if (data.faqItems) {
    for (let i = 0; i < data.faqItems.length; i++) {
      const faq = data.faqItems[i]
      const faqId = `${data.id}-faq-${i + 1}`
      sql.push(`INSERT OR IGNORE INTO faq_items (id, [group], service_id, status, sort_order) VALUES ('${faqId}', 'SERVICE', '${data.id}', 'PUBLISHED', ${i + 1});`)
      sql.push(`INSERT OR IGNORE INTO faq_item_translations (id, faq_item_id, locale, question, answer) VALUES ('${faqId}-ru', '${faqId}', 'ru', '${sqlEscape(faq.question)}', '${sqlEscape(faq.answer)}');`)
    }
  }
  sql.push('')
}

// ═══════════════════════════════════════════════════
// 3. EXISTING SERVICE REWRITES (6)
// ═══════════════════════════════════════════════════
const rewriteFiles = readdirSync(DIR).filter(f => f.startsWith('rewrite-') && f.endsWith('.json'))
sql.push('-- ═══ Existing Service Rewrites ═══')
for (const f of rewriteFiles) {
  const data = JSON.parse(readFileSync(join(DIR, f), 'utf8'))
  const slugBase = data.slugBase
  const ts = now()
  const ru = data.ru
  const seo = data.seo
  sql.push(`UPDATE service_translations SET title = '${sqlEscape(ru.title)}', short_title = '${sqlEscape(ru.shortTitle)}', description = '${sqlEscape(ru.description)}', hero_title = '${sqlEscape(ru.heroTitle)}', hero_subtitle = '${sqlEscape(ru.heroSubtitle)}', faq_json = '${sqlEscape(ru.faqJson)}' WHERE service_id = (SELECT id FROM services WHERE slug_base = '${slugBase}') AND locale = 'ru';`)
  sql.push(`INSERT OR REPLACE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${slugBase}-ru', 'service', (SELECT id FROM services WHERE slug_base = '${slugBase}'), 'ru', '${sqlEscape(seo.title)}', '${sqlEscape(seo.description)}', '${seo.canonicalPath}', '${ts}', '${ts}');`)
  // SEO UK for rewrites — derive from existing UK translation or use RU canonical with /uk/ prefix
  const ukCanonical = seo.canonicalPath.replace('/ru/', '/uk/')
  sql.push(`INSERT OR REPLACE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${slugBase}-uk', 'service', (SELECT id FROM services WHERE slug_base = '${slugBase}'), 'uk', '${sqlEscape(seo.title)}', '${sqlEscape(seo.description)}', '${ukCanonical}', '${ts}', '${ts}');`)
  // FAQ items
  if (ru.faqJson) {
    const faqs = JSON.parse(ru.faqJson)
    for (let i = 0; i < faqs.length; i++) {
      const faqId = `${slugBase}-faq-${i + 1}`
      sql.push(`INSERT OR IGNORE INTO faq_items (id, [group], service_id, status, sort_order) VALUES ('${faqId}', 'SERVICE', (SELECT id FROM services WHERE slug_base = '${slugBase}'), 'PUBLISHED', ${i + 1});`)
      sql.push(`INSERT OR IGNORE INTO faq_item_translations (id, faq_item_id, locale, question, answer) VALUES ('${faqId}-ru', '${faqId}', 'ru', '${sqlEscape(faqs[i].question)}', '${sqlEscape(faqs[i].answer)}');`)
    }
  }
  sql.push('')
}

// ═══════════════════════════════════════════════════
// 4. BLOG POSTS (8)
// ═══════════════════════════════════════════════════
const blogFiles = readdirSync(DIR).filter(f => f.startsWith('blog-') && f.endsWith('.json'))
sql.push('-- ═══ Blog Posts ═══')
for (const f of blogFiles) {
  const data = JSON.parse(readFileSync(join(DIR, f), 'utf8'))
  const postId = `post-${data.slugBase}`
  const ts = now()
  const ru = data.ru
  const seo = data.seo
  // Find matching placeholder image
  const imgId = placeholderImages.find(img => img.slug === ru.slug)?.id || null
  sql.push(`INSERT OR IGNORE INTO blog_posts (id, category_id, status, cover_image_id, reading_minutes, published_at, created_at, updated_at) VALUES ('${postId}', '${data.categoryId}', 'PUBLISHED', ${imgId ? `'${imgId}'` : 'NULL'}, ${data.readingMinutes}, '${ts}', '${ts}', '${ts}');`)
  sql.push(`INSERT OR IGNORE INTO blog_post_translations (id, post_id, locale, slug, title, excerpt, content_html, faq_json) VALUES ('${postId}-ru', '${postId}', 'ru', '${ru.slug}', '${sqlEscape(ru.title)}', '${sqlEscape(ru.excerpt)}', '${sqlEscape(ru.contentHtml)}', '${sqlEscape(ru.faqJson)}');`)
  // SEO RU
  sql.push(`INSERT OR IGNORE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${postId}-ru', 'blog_post', '${postId}', 'ru', '${sqlEscape(seo.title)}', '${sqlEscape(seo.description)}', '${seo.canonicalPath}', '${ts}', '${ts}');`)
  // SEO UK
  const ukCanonical = seo.canonicalPath.replace('/ru/', '/uk/')
  sql.push(`INSERT OR IGNORE INTO seo_meta (id, entity_type, entity_id, locale, title, description, canonical_path, created_at, updated_at) VALUES ('seo-${postId}-uk', 'blog_post', '${postId}', 'uk', '${sqlEscape(seo.title)}', '${sqlEscape(seo.description)}', '${ukCanonical}', '${ts}', '${ts}');`)
  sql.push('')
}

// ═══════════════════════════════════════════════════
// Write SQL file
// ═══════════════════════════════════════════════════
const outPath = join(DIR, 'seed.sql')
writeFileSync(outPath, sql.join('\n'), 'utf8')
console.log(`Generated ${sql.length} SQL statements → ${outPath}`)
console.log('')
console.log('Steps:')
console.log('  1. node scripts/seo-seed.mjs')
console.log('  2. npx wrangler d1 execute podvarchan --file=TEMP/seo-content/seed.sql --remote')
console.log('  3. node scripts/seo-revalidate.mjs')
